FROM debian:bullseye

RUN apt-get update && apt-get install -y bash gcc tini procps

COPY zombie.c /zombie.c
RUN gcc /zombie.c -o /zombie && rm /zombie.c

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["/zombie"]
